### ISSUE TITLE
KT-25396 - KAPT sample error: Unknown option: infoAsWarnings

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#959]
Broken the `hello-kapt` sample after the upgrade to Kotlin 1.2.60-eap-44.

The sample test should be un-ignored once this is fixed.

**Comment by eskatos** [comment]
I was able to make it work with kotlin 1.2.51 and auto-value 1.6.2 after changing the dependencies to use `auto-value-annotations` on `compileOnly`. But then it fails with kotlin 1.2.60-eap-44 with the following error:

```
➜  hello-kapt git:(develop) ./gradlew classes
e: Unknown option: infoAsWarnings
> Task :kaptGenerateStubsKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kaptGenerateStubsKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

To reproduce, checkout `develop` branch, `cd` into `samples/hello-kapt` and run `./gradlew classes`.

**Comment by eskatos** [comment]
This is due to a regression in 1.2.60-eap-44, see https://youtrack.jetbrains.com/issue/KT-25396

**Comment by eskatos** [comment]
Fixed in 1.2.60-eap-74, closing, see 6d46d72e4c8cc156c9d64461d3cf623d96705b1e
