### ISSUE TITLE
Package-default nullability annotations are supported

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#463]
From the [Kotlin 1.1.4 announcement](https://blog.jetbrains.com/kotlin/2017/08/kotlin-1-1-4-is-out/):

> Starting with this release, Kotlin supports package-default nullability annotations (such as JSR-305’s @ParametersAreNonnullByDefault and the @NonNullApi annotation introduced in Spring Framework 5.0). To facilitate migration and avoid compilation errors due to more precise nullability information on used Java APIs, the support for such annotations is off by default, and needs to be enabled by passing the -Xjsr305-annotations=enable command line option to the compiler.

**Comment by sdeleuze** [comment]
Glad you plan to support that :-)

**Comment by eskatos** [comment]
Blocked by #506

**Comment by bamboo** [comment]
Fix implemented in 4fc15ec and confirmed to work with the Kotlin plugin version 1.2.40-release-IJ2018.1-1:

<img width="715" alt="jsr305" src="https://user-images.githubusercontent.com/51689/39084887-3a96f22e-4552-11e8-8b15-8e296488826d.png">

Type of expression `project.file(...)` is inferred as the non-null `File` type as expected and no longer as the platform type `File!`.
